Flying:
    InitialEXPCost: 10
    EXPCostPerSecond: 1
    MinExpToStartFlying: 30

system:
    # Change this to get you and this plugin eaten by Ender Dragon, not really, seriously.
    PluginVersion: ${version}